//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppException
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Message { get; set; }
        public string Detail { get; set; }
        public System.DateTime OccuredDate { get; set; }
    }
}
