//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleAttributeDefinition
    {
        public ArticleAttributeDefinition()
        {
            this.ArticleAttributeValues = new HashSet<ArticleAttributeValue>();
        }
    
        public int Id { get; set; }
        public int ArticleCategoryId { get; set; }
        public string AttrName { get; set; }
        public string InitialValue { get; set; }
        public string AttrDescription { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public AttributeValueType ValueType { get; set; }
    
        public virtual ICollection<ArticleAttributeValue> ArticleAttributeValues { get; set; }
    }
}
