//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCategory
    {
        public ArticleCategory()
        {
            this.EnableComment = true;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool EnableComment { get; set; }
        public bool EnableAttachment { get; set; }
        public int DisplayOrder { get; set; }
    }
}
