//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileExtensionName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public Nullable<int> BOId { get; set; }
        public Nullable<BusinessObjectType> BOType { get; set; }
        public bool IsImage { get; set; }
    }
}
