//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    
    [Flags]
    public enum ContentType : int
    {
        Link = 10,
        SinglePage = 20,
        Article = 30,
        Resource = 40
    }
}
