//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    
    public enum MenuCategory : short
    {
        Main = 0,
        Secondary = 1,
        Third = 2,
        Fourth = 3
    }
}
