//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string ShortText { get; set; }
        public string Icon { get; set; }
        public string Uri { get; set; }
        public MenuCategory Category { get; set; }
        public ContentType ContentType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsHidden { get; set; }
    }
}
