//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockInfo> BlockInfoes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<SinglePage> SinglePages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<UserRights> UserRights { get; set; }
        public virtual DbSet<AppException> AppExceptions { get; set; }
        public virtual DbSet<ArticleAttributeDefinition> ArticleAttributeDefinitions { get; set; }
        public virtual DbSet<ArticleAttributeValue> ArticleAttributeValues { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceDirectory> ResourceDirectories { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
