//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavInfo
    {
        public int Id { get; set; }
        public string NavText { get; set; }
        public string NavShortText { get; set; }
        public string NavIcon { get; set; }
        public string NavUri { get; set; }
        public NavType NavType { get; set; }
        public ContentType ContentType { get; set; }
        public Nullable<int> ParentNavId { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    }
}
