//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePage
    {
        public SinglePage()
        {
            this.EnableComment = true;
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Views { get; set; }
        public string Content { get; set; }
        public bool EnableComment { get; set; }
        public Nullable<bool> EnableAttachment { get; set; }
        public bool HasImageAttachments { get; set; }
    }
}
