//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
        public UserRole Role { get; set; }
        public string GroupIds { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
    }
}
